[project]
name = "extract-public"
version = "0.1.0"
description = "LBM Extract Demo"
readme = "README.md"
requires-python = ">=3.10, <=3.11"

dependencies = [
    "h5py",
    "lbm_suite2p_python",
    "mbo_utilities",
    "napari>=0.5.6",
    "PyQt5",
]

[tool.uv.sources]
lbm_suite2p_python = { git = "https://github.com/MillerBrainObservatory/LBM-Suite2p-Python", branch = "master" }
mbo_utilities = { git = "https://github.com/MillerBrainObservatory/mbo_utilities", branch = "master" }
